server:
  port: 8085
  indexingAvailable: true

spring.profiles.active: mysql
#spring.profiles.active: postgresql

spring.jpa.show-sql: false

spring:
  jpa.properties.hibernate.enable_lazy_load_no_trans: true

  thymeleaf:
    enabled: true
    encoding: UTF-8

  messages.basename: lang.messages

#  main:
#    banner-mode: off

logging:
  level.root: INFO
  file.name: logs/info.log

config:
  forSitesThreadNumber: 12
  forPagesThreadNumber: 12
  repeatedPageCount: 14
  maxPagesInSite: 2000

  sites:
    - url: https://www.tretyakovgallery.ru/
      name: Niko ART GALLERY
      pause: 0
